# 0x05 Python - Exceptions

This project is part of the ALx software engineering programme.

The aim of this project is to learn the folliwng:
- What's the difference between errors and exceptions
- What are exceptions and how to use them
- When do we need to use exceptions
- How to correctly handle an exception
- What's the purpose of catching exceptions
- How to raise a builtint exception
- When do we need to implement a clean-up action after an exception

| S/N | File(s) | Description |
| --- | ------- | ----------- |
| 0 | [0-safe_print_list.py](./0-safe_print_list.py) | A function that prints `x` elements of a list |
| 1 | [1-safe_print_integer.py](./1-safe_print_integer.py) | A function that prints an integer with `"{:d}".format()` |
| 2 | [2-safe_print_list_integers.py](./2-safe_print_list_integers.py) | A function that prints the first `x` elements of a list and only integers |
| 3 | [3-safe_print_division.py](./3-safe_print_division.py) | A function that divides 2 integers and prints the result |
| 4 | [4-list_division.py](./4-list_division.py) | A function that divides element by element 2 lists |
| 5 | [5-raise_exception.py](./5-raise_exception.py) | A function that raises a type exception |
| 6 | [6-raise_exception_msg.py](./6-raise_exception_msg.py) | A function that raises a name exception with a messsage|
| 7 | [100-safe_print_integer_err.py](./100-safe_print_integer_err.py) | A function that prints an integer |
| 8 | [101-safe_function.py](./101-safe_function.py) | A function that executes a function safely |  
